clientWebServer:
  clientWebServer:
    env:
      apiServerIp: "apiserverchart-service.default.svc.cluster.local"
      kafkaIp: "kafkachart-kafka-helm-b.default.svc.cluster.local"
    image:
      repository: oraharon/web-store-fe
      tag: "6"
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  type: ClusterIP
